/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CustomEdge: typeof import('./components/CustomEdge.vue')['default']
    CustomeNode: typeof import('./components/MyNode.vue')['default']
    Dialog: typeof import('./components/common/Dialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MyEdge: typeof import('./components/MyEdge.vue')['default']
    MyNode: typeof import('./components/MyNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
